version: "3"

tasks:

  setup:
    desc: "Install system dependencies"
    cmds:
      - echo "ðŸ” Checking system requirements..."

      # uv
      - |
        if ! command -v uv >/dev/null 2>&1; then
          echo "ðŸ“¦ Installing uv..."
          if [[ "$OSTYPE" == "darwin"* ]]; then
            brew install uv
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
        else
          echo "âœ… uv already installed."
        fi

      # Taskfile
      - |
        if ! command -v task >/dev/null 2>&1; then
          echo "ðŸ“¦ Installing Taskfile..."
          if [[ "$OSTYPE" == "darwin"* ]]; then
            brew install go-task/tap/go-task
          else
            sh -fsSL https://taskfile.dev/install.sh | sh
          fi
        else
          echo "âœ… Taskfile already installed."
        fi

      # Python
      - |
        if ! command -v python3 >/dev/null 2>&1; then
          echo "ðŸ“¦ Installing Python..."
          brew install python
        else
          echo "âœ… Python already installed."
        fi

      # Node.js
      - |
        if ! command -v node >/dev/null 2>&1; then
          echo "ðŸ“¦ Installing Node.js..."
          brew install node
        else
          echo "âœ… Node.js already installed."
        fi

      # Bun
      - |
        if ! command -v bun >/dev/null 2>&1; then
          echo "ðŸ“¦ Installing Bun..."
          curl -fsSL https://bun.sh/install | bash
        else
          echo "âœ… Bun already installed."
        fi


  install:
    desc: "Install backend + frontend dependencies"
    cmds:
      - echo "ðŸ“¦ Installing backend dependencies..."
      - uv sync

      - echo "ðŸ“¦ Installing frontend dependencies..."
      - cd frontend && bun install

      - echo "âœ… Installation complete!"


  backend:
    desc: "Start FastAPI backend"
    cmds:
      - echo "ðŸš€ Starting backend at http://localhost:8000"
      - .venv/bin/uvicorn backend.app:app --reload --host 0.0.0.0 --port 8000


  frontend:
    desc: "Run Vite frontend"
    dir: frontend
    cmds:
      - echo "ðŸš€ Starting frontend at http://localhost:8080"
      - bun dev


  open-browser:
    desc: "Open browser"
    cmds:
      - |
        echo "ðŸŒ Opening browser..."
        sleep 2
        if command -v open >/dev/null 2>&1; then
          open http://localhost:8080
        elif command -v xdg-open >/dev/null 2>&1; then
          xdg-open http://localhost:8080
        fi


  app:
    desc: "Run full stack (backend + frontend)"
    cmds:
      - task backend &
      - task frontend &
      - task open-browser
      - wait


  end:
    desc: "Cleanly stop backend + frontend"
    cmds:
      - echo "ðŸ›‘ Stopping services..."

      - |
        echo "ðŸ”ª Killing uvicorn..."
        pgrep -f "backend.app:app" | xargs kill -9 2>/dev/null || true

      - |
        echo "ðŸ”ª Killing Python backend..."
        pkill -f "backend/app.py" || true

      - |
        echo "ðŸ”ª Killing frontend..."
        pgrep -f "bun dev" | xargs kill -9 2>/dev/null || true
        pgrep -f "vite" | xargs kill -9 2>/dev/null || true

      - |
        echo "ðŸ§¹ Freeing ports 8000 and 8080..."
        lsof -ti :8000 | xargs kill -9 2>/dev/null || true
        lsof -ti :8080 | xargs kill -9 2>/dev/null || true

      - echo "âœ… All services stopped."